default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "dev_app" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "dev_secret" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: good_night_development

test:
  <<: *default
  database: good_night_test

production:
  <<: *default
  host: db
  database: <%= ENV.fetch("POSTGRES_DB") { "good_night" } %>

