default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME") { "dev_app" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "dev_secret" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: good_night_dev

production:
  <<: *default
  database: good_night

test:
  <<: *default
  database: storage/test.sqlite3
  adapter: sqlite3

